title: Chuan Yan
position: Postdoc Researcher
affiliation: Stanford University
email: chuanyan@stanford.edu
keywords: Chuan Yan,
description: Chuan Yan's personal homepage.
canonical: https://nauhcnay.github.io/
google_scholar: https://scholar.google.com/citations?user=z0VFLowAAAAJ&hl=en
cv_link: assets/files/ChuanYan_CV_Ind.pdf
github_link: https://github.com/Nauhcnay
linkedin: https://www.linkedin.com/in/chuan-yan-8b4074198/
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
enable_footnote: true
auto_dark_mode: true
font: Serif
remote_theme: yaoyao-liu/minimal-light
exclude:
- Gemfile
- Gemfile.lock
- README.md
- README_zh_Hans.md
- README_zh_Hant.md
- README_de.md
- LICENSE
- minimal-light.gemspec
- html_source_file/
